// @generated by usergist
package studio.usergist.feedback.expo

import com.google.firebase.messaging.RemoteMessage
import expo.modules.notifications.service.ExpoFirebaseMessagingService
import studio.usergist.feedback.UserGistFirebaseMessagingService

class UserGistExpoMessagingService : ExpoFirebaseMessagingService() {
  override fun onMessageReceived(message: RemoteMessage) {
    if (message.data.containsKey("usergist_campaign_id") || message.data["usergist_silent"] == "1") {
      UserGistFirebaseMessagingService.handleMessage(this, message)
    } else {
      super.onMessageReceived(message)
    }
  }
  override fun onNewToken(token: String) {
    super.onNewToken(token)
    UserGistFirebaseMessagingService.handleToken(token)
  }
}
