'use strict'
const fs = require('node:fs')
const path = require('node:path')
const { createHash } = require('node:crypto')
const {
  createRunOncePlugin, withInfoPlist, withEntitlementsPlist, withXcodeProject,
  withPodfile, withAndroidManifest, withAppBuildGradle, withProjectBuildGradle,
  withDangerousMod,
} = require('expo/config-plugins')
const { version } = require('../package.json')
const marker = '// @generated by usergist'
const fail = message => { throw new Error(`[UserGist Expo] ${message}`) }
const unique = values => [...new Set(values)]
const identifier = (value, label) => {
  if (!/^[A-Za-z0-9][A-Za-z0-9.-]+$/.test(value)) fail(`Invalid ${label}: ${value}`)
  return value
}

function settings(config, options = {}) {
  const push = options.push
  if (!push) return null
  if (!['automatic', 'expo-notifications'].includes(push.mode)) fail('push.mode must be automatic or expo-notifications')
  const result = { ...push }
  if (config.platforms?.includes('ios') !== false) {
    const bundle = config.ios?.bundleIdentifier
    if (!bundle) fail('Set ios.bundleIdentifier before configuring push')
    if (!['development', 'production'].includes(push.ios?.apsEnvironment)) {
      fail('Set push.ios.apsEnvironment from the signing profile (development or production), not the UserGist data environment')
    }
    const target = push.ios.extensionTargetName || 'UserGistNotificationServiceExtension'
    if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(target)) fail('extensionTargetName must be a valid Swift/Xcode identifier')
    result.ios = {
      ...push.ios, extensionTargetName: target,
      appGroupIdentifier: identifier(push.ios.appGroupIdentifier || `group.${bundle}.usergist`, 'App Group'),
      extensionBundleIdentifier: identifier(push.ios.extensionBundleIdentifier || `${bundle}.${target}`, 'extension bundle identifier'),
    }
    if (!result.ios.extensionBundleIdentifier.startsWith(`${bundle}.`)) fail('The extension bundle identifier must be prefixed by ios.bundleIdentifier')
  }
  if (push.android?.notificationColor && !/^#[0-9a-f]{6}$/i.test(push.android.notificationColor)) fail('notificationColor must be #RRGGBB')
  return result
}

function writeOwned(file, content, ownedTarget = false) {
  if (fs.existsSync(file) && !ownedTarget && !fs.readFileSync(file, 'utf8').includes(marker)) fail(`Existing file is not owned by UserGist: ${file}. See /docs/sdks/expo#conflicts`)
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, content)
}

function withUserGist(config, options = {}) {
  const push = settings(config, options)
  const plugins = (config.plugins || []).map(p => Array.isArray(p) ? p[0] : p)
  if (push?.mode === 'automatic' && plugins.includes('expo-notifications')) {
    fail('expo-notifications is configured. Select push.mode="expo-notifications" to preserve its handlers')
  }
  if (push?.mode === 'expo-notifications' && !plugins.includes('expo-notifications')) {
    fail('Install expo-notifications and add its plugin before the UserGist plugin')
  }
  config = withInfoPlist(config, c => {
    c.modResults.UserGistExpo = true
    c.modResults.UserGistPushMode = push?.mode || 'disabled'
    if (push?.ios) {
      c.modResults.UserGistAppGroup = push.ios.appGroupIdentifier
      c.modResults.UserGistApsEnvironment = push.ios.apsEnvironment
      c.modResults.UIBackgroundModes = unique([...(c.modResults.UIBackgroundModes || []), 'remote-notification'])
    }
    return c
  })
  config = withAndroidManifest(config, c => {
    const manifest = c.modResults.manifest
    manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools'
    const app = manifest.application[0]
    app['meta-data'] ||= []
    for (const [name, value] of [['UserGistExpo', 'true'], ['UserGistPushMode', push?.mode || 'disabled']]) {
      const old = app['meta-data'].find(m => m.$['android:name'] === name)
      if (old) old.$['android:value'] = value
      else app['meta-data'].push({ $: { 'android:name': name, 'android:value': value } })
    }
    const services = app.service ||= []
    const dispatcher = 'studio.usergist.feedback.expo.UserGistExpoMessagingService'
    const owns = new Set([dispatcher, 'studio.usergist.feedback.UserGistFirebaseMessagingService', 'expo.modules.notifications.service.ExpoFirebaseMessagingService'])
    for (const service of services) {
      if (push && (service['intent-filter'] || []).some(f => (f.action || []).some(a => a.$['android:name'] === 'com.google.firebase.MESSAGING_EVENT')) && !owns.has(service.$['android:name'])) {
        fail(`Custom FCM service ${service.$['android:name']} requires explicit host integration; see /docs/sdks/expo#conflicts`)
      }
    }
    const setService = (name, enabled) => {
      let service = services.find(s => s.$['android:name'] === name)
      if (!service) services.push(service = { $: { 'android:name': name } })
      Object.assign(service.$, { 'android:enabled': String(enabled), 'tools:replace': 'android:enabled' })
    }
    setService('studio.usergist.feedback.UserGistFirebaseMessagingService', push?.mode === 'automatic')
    if (push?.mode === 'expo-notifications') {
      setService('expo.modules.notifications.service.ExpoFirebaseMessagingService', false)
      let service = services.find(s => s.$['android:name'] === dispatcher)
      if (!service) services.push(service = { $: { 'android:name': dispatcher } })
      Object.assign(service.$, { 'android:exported': 'false', 'android:enabled': 'true' })
      service['intent-filter'] = [{ action: [{ $: { 'android:name': 'com.google.firebase.MESSAGING_EVENT' } }] }]
    } else if (services.some(s => s.$['android:name'] === dispatcher)) {
      fail('Changing push ownership in an existing native project requires a fresh generated project; see /docs/sdks/expo#conflicts')
    }
    if (push?.android?.notificationIcon) {
      app['meta-data'].push({ $: { 'android:name': 'UserGistNotificationIcon', 'android:resource': '@drawable/usergist_notification_icon' } })
      app['meta-data'] = app['meta-data'].filter((m, i, a) => a.findIndex(n => n.$['android:name'] === m.$['android:name']) === i)
    }
    if (push?.android?.notificationColor) {
      const name = 'UserGistNotificationColor'
      app['meta-data'] = app['meta-data'].filter(m => m.$['android:name'] !== name)
      app['meta-data'].push({ $: { 'android:name': name, 'android:value': push.android.notificationColor } })
    }
    return c
  })
  if (!push) return config

  if (config.platforms?.includes('android') !== false) {
    if (!config.android?.googleServicesFile) fail('Set android.googleServicesFile to your Firebase client google-services.json (not a service-account key)')
    config = withProjectBuildGradle(config, c => {
      if (c.modResults.language && c.modResults.language !== 'groovy') fail('Kotlin Gradle configuration requires explicit Google Services integration; see /docs/sdks/expo#conflicts')
      if (!c.modResults.contents.includes('com.google.gms:google-services:')) {
        if (!/dependencies\s*\{/.test(c.modResults.contents)) fail('Unsupported project Gradle format; add the Google Services classpath explicitly')
        c.modResults.contents = c.modResults.contents.replace(/dependencies\s*\{/, "dependencies {\n        classpath('com.google.gms:google-services:4.4.4')")
      }
      return c
    })
    config = withAppBuildGradle(config, c => {
      if (c.modResults.language && c.modResults.language !== 'groovy') fail('Kotlin Gradle configuration requires an explicit notification dispatcher dependency; see /docs/sdks/expo#conflicts')
      if (!/apply plugin: ['"]com.google.gms.google-services['"]/.test(c.modResults.contents)) c.modResults.contents += '\napply plugin: "com.google.gms.google-services"\n'
      if (push.mode === 'expo-notifications') {
        const folder = path.dirname(require.resolve('expo-notifications/package.json', { paths: [c.modRequest.projectRoot] }))
        const publication = JSON.parse(fs.readFileSync(path.join(folder, 'expo-module.config.json'), 'utf8')).android?.publication
        const fallback = publication ? `implementation("${publication.groupId}:${publication.artifactId}:${publication.version}")` : `throw new GradleException("expo-notifications is not autolinked")`
        const stanza = `// usergist-expo-dispatch\ndependencies { if (findProject(":expo-notifications") != null) { implementation project(":expo-notifications") } else { ${fallback} } }\n// usergist-expo-dispatch-end`
        if (c.modResults.contents.includes('// usergist-expo-dispatch-end')) c.modResults.contents = c.modResults.contents.replace(/\/\/ usergist-expo-dispatch[\s\S]*?\/\/ usergist-expo-dispatch-end/, stanza)
        else if (c.modResults.contents.includes('// usergist-expo-dispatch')) c.modResults.contents = c.modResults.contents.replace(/\/\/ usergist-expo-dispatch\ndependencies \{ implementation project\(":expo-notifications"\) \}/, stanza)
        else c.modResults.contents += `\n${stanza}\n`
      }
      return c
    })
    config = withDangerousMod(config, ['android', async c => {
      const root = c.modRequest.platformProjectRoot
      if (push.mode === 'automatic') {
        let installed = false
        try { require.resolve('expo-notifications/package.json', { paths: [c.modRequest.projectRoot] }); installed = true } catch {}
        if (installed) fail('expo-notifications is installed and autolinks its FCM service. Select push.mode="expo-notifications" and add its plugin to preserve notification ownership')
      }
      const google = path.resolve(c.modRequest.projectRoot, c.android.googleServicesFile)
      const json = JSON.parse(fs.readFileSync(google, 'utf8'))
      if (!json.client?.some(client => client.client_info?.android_client_info?.package_name === c.android.package)) fail('google-services.json does not contain android.package')
      if (push.mode === 'expo-notifications') {
        const template = fs.readFileSync(path.join(__dirname, 'templates/UserGistExpoMessagingService.kt'), 'utf8')
        writeOwned(path.join(root, 'app/src/main/java/studio/usergist/feedback/expo/UserGistExpoMessagingService.kt'), template)
      }
      if (push.android?.notificationIcon) {
        const file = path.resolve(c.modRequest.projectRoot, push.android.notificationIcon)
        if (path.extname(file).toLowerCase() !== '.png') fail('notificationIcon must be a white-on-transparent PNG')
        const dest = path.join(root, 'app/src/main/res/drawable/usergist_notification_icon.png')
        fs.mkdirSync(path.dirname(dest), { recursive: true })
        const ownershipFile = path.join(root, '.usergist-expo-assets.json')
        const ownership = fs.existsSync(ownershipFile) ? JSON.parse(fs.readFileSync(ownershipFile, 'utf8')) : { owner: '@usergist/feedback-react-native', files: {} }
        if (ownership.owner !== '@usergist/feedback-react-native') fail(`Asset ownership file is not owned by UserGist: ${ownershipFile}`)
        const asset = path.relative(root, dest)
        const hash = bytes => createHash('sha256').update(bytes).digest('hex')
        if (fs.existsSync(dest) && !fs.readFileSync(dest).equals(fs.readFileSync(file)) && ownership.files[asset] !== hash(fs.readFileSync(dest))) fail('Notification icon was customized outside the plugin; preserve it and follow /docs/sdks/expo#conflicts')
        fs.copyFileSync(file, dest)
        ownership.files[asset] = hash(fs.readFileSync(dest))
        fs.writeFileSync(ownershipFile, JSON.stringify(ownership))
      }
      return c
    }])
  }
  if (push.ios) config = withExtension(config, push.ios)
  return config
}

function withExtension(config, ios) {
  const target = ios.extensionTargetName
  const group = ios.appGroupIdentifier
  const entry = { targetName: target, bundleIdentifier: ios.extensionBundleIdentifier, entitlements: { 'com.apple.security.application-groups': [group] } }
  config.extra ||= {}; config.extra.eas ||= {}; config.extra.eas.build ||= {}
  config.extra.eas.build.experimental ||= {}; config.extra.eas.build.experimental.ios ||= {}
  const extensions = config.extra.eas.build.experimental.ios.appExtensions ||= []
  const old = extensions.find(e => e.targetName === target || e.bundleIdentifier === entry.bundleIdentifier)
  if (old && JSON.stringify(old) !== JSON.stringify(entry)) fail('Conflicting EAS extension configuration; preserve the existing extension and follow /docs/sdks/expo#conflicts')
  if (!old) extensions.push(entry)
  config = withEntitlementsPlist(config, c => {
    c.modResults['aps-environment'] = ios.apsEnvironment
    c.modResults['com.apple.security.application-groups'] = unique([...(c.modResults['com.apple.security.application-groups'] || []), group])
    return c
  })
  config = withPodfile(config, c => {
    const begin = '# usergist-extension-begin'
    const stanza = `${begin}\ntarget '${target}' do\n  pod 'UserGistFeedbackExtension', :path => File.dirname(\`node --print "require.resolve('@usergist/feedback-react-native/package.json')"\`.strip)\nend\n# usergist-extension-end`
    if (c.modResults.contents.includes(begin)) c.modResults.contents = c.modResults.contents.replace(/# usergist-extension-begin[\s\S]*?# usergist-extension-end/, stanza)
    else {
      if (c.modResults.contents.includes(`target '${target}'`) || c.modResults.contents.includes(`target "${target}"`)) fail('Existing extension Podfile target is not owned by UserGist')
      c.modResults.contents += `\n${stanza}\n`
    }
    return c
  })
  config = withXcodeProject(config, c => {
    const project = c.modResults
    const root = c.modRequest.platformProjectRoot
    const folder = path.join(root, target)
    const swift = path.join(folder, 'NotificationService.swift')
    const ownsFolder = fs.existsSync(swift) && fs.readFileSync(swift, 'utf8').includes(marker)
    const targets = project.pbxNativeTargetSection()
    for (const [key, native] of Object.entries(targets)) {
      if (key.endsWith('_comment') || String(native.name).replaceAll('"', '') === target) continue
      if (String(native.productType).includes('app-extension')) {
        const list = project.pbxXCConfigurationList()[native.buildConfigurationList]
        for (const ref of list?.buildConfigurations || []) {
          const settings = project.pbxXCBuildConfigurationSection()[ref.value].buildSettings
          const name = String(settings.INFOPLIST_FILE || '').replaceAll('"', '').replace(/\$\((?:SRCROOT|PROJECT_DIR)\)|\$\{(?:SRCROOT|PROJECT_DIR)\}/g, root).replace(/\$\(TARGET_NAME\)/g, String(native.name).replaceAll('"', ''))
          const file = path.resolve(root, name)
          if (!name || name.includes('$') || !fs.existsSync(file)) fail(`Cannot inspect Info.plist for existing app extension ${native.name}; verify notification ownership explicitly, see /docs/sdks/expo#conflicts`)
          if (name && fs.existsSync(file) && fs.readFileSync(file, 'utf8').includes('com.apple.usernotifications.service')) fail(`Existing notification service extension ${native.name} needs manual composition; see /docs/sdks/expo#conflicts`)
        }
      }
    }
    let found = Object.entries(targets).find(([key, t]) => !key.endsWith('_comment') && String(t.name).replaceAll('"', '') === target)
    if (found && (!fs.existsSync(swift) || !fs.readFileSync(swift, 'utf8').includes(marker))) fail(`Xcode target ${target} already exists and is not owned by UserGist`)
    // Xcode project generation runs after the standard Expo native template exists.
    writeOwned(swift, `${marker}\nimport UserGistFeedbackExtension\nclass NotificationService: UserGistNotificationService {}\n`)
    const plist = require('@expo/plist').default
    const info = { CFBundleDisplayName: target, CFBundleIdentifier: '$(PRODUCT_BUNDLE_IDENTIFIER)', CFBundleExecutable: '$(EXECUTABLE_NAME)', CFBundleName: '$(PRODUCT_NAME)', CFBundlePackageType: 'XPC!', CFBundleShortVersionString: c.version || '1.0.0', CFBundleVersion: c.ios?.buildNumber || '1', UserGistExpo: true, UserGistAppGroup: group, NSExtension: { NSExtensionPointIdentifier: 'com.apple.usernotifications.service', NSExtensionPrincipalClass: '$(PRODUCT_MODULE_NAME).NotificationService' } }
    for (const [file, value] of [['Info.plist', info], [`${target}.entitlements`, entry.entitlements]]) {
      const destination = path.join(folder, file)
      const existing = ownsFolder && fs.existsSync(destination) ? plist.parse(fs.readFileSync(destination, 'utf8')) : {}
      const merged = { ...existing, ...value }
      if (value.NSExtension) merged.NSExtension = { ...existing.NSExtension, ...value.NSExtension }
      if (value['com.apple.security.application-groups']) merged['com.apple.security.application-groups'] = unique([...(existing['com.apple.security.application-groups'] || []), group])
      const xml = plist.build(merged).replace('<plist version="1.0">', `<!-- ${marker} -->\n<plist version="1.0">`)
      writeOwned(destination, xml, ownsFolder)
    }
    project.hash.project.objects.PBXTargetDependency ||= {}
    project.hash.project.objects.PBXContainerItemProxy ||= {}
    if (!found) {
      const native = project.addTarget(target, 'app_extension', target, ios.extensionBundleIdentifier)
      const groupEntry = project.addPbxGroup([], target, target)
      project.addToPbxGroup(groupEntry.uuid, project.getFirstProject().firstProject.mainGroup)
      project.addBuildPhase([], 'PBXSourcesBuildPhase', 'Sources', native.uuid)
      project.addBuildPhase([], 'PBXFrameworksBuildPhase', 'Frameworks', native.uuid)
      project.addBuildPhase([], 'PBXResourcesBuildPhase', 'Resources', native.uuid)
      project.addSourceFile('NotificationService.swift', { target: native.uuid }, groupEntry.uuid)
      // addTarget adds the embed phase and target dependency for app extensions.
      found = [native.uuid, native.pbxNativeTarget]
    }
    const host = project.getFirstTarget()
    const dependencies = project.hash.project.objects.PBXTargetDependency
    if (!host.firstTarget.dependencies.some(ref => dependencies[ref.value]?.target === found[0])) project.addTargetDependency(host.uuid, [found[0]])
    for (const ref of Object.values(project.pbxFileReferenceSection())) {
      if (ref && typeof ref === 'object' && String(ref.path).replaceAll('"', '') === `${target}/NotificationService.swift`) ref.path = '"NotificationService.swift"'
    }
    const list = project.pbxXCConfigurationList()[found[1].buildConfigurationList]
    for (const ref of list.buildConfigurations) {
      const build = project.pbxXCBuildConfigurationSection()[ref.value].buildSettings
      Object.assign(build, { INFOPLIST_FILE: `"${target}/Info.plist"`, CODE_SIGN_ENTITLEMENTS: `"${target}/${target}.entitlements"`, PRODUCT_BUNDLE_IDENTIFIER: `"${ios.extensionBundleIdentifier}"`, SWIFT_VERSION: '5.0', IPHONEOS_DEPLOYMENT_TARGET: '15.1', TARGETED_DEVICE_FAMILY: '"1,2"', SKIP_INSTALL: 'YES', APPLICATION_EXTENSION_API_ONLY: 'YES', GENERATE_INFOPLIST_FILE: 'NO' })
      if (c.ios?.appleTeamId) build.DEVELOPMENT_TEAM = c.ios.appleTeamId
    }
    return c
  })
  return config
}
module.exports = createRunOncePlugin(withUserGist, '@usergist/feedback-react-native', version)
module.exports.withUserGist = withUserGist
module.exports.settings = settings
