export const webStyles = `
:host{all:initial;display:block;container-type:inline-size;font-family:var(--ug-font,Inter,system-ui,sans-serif);color:var(--ug-text,#15151D)}
*{box-sizing:border-box}button,input,textarea,select{font:inherit}button{cursor:pointer}button:disabled{cursor:default;opacity:.5}button,input,textarea,select{outline-offset:3px} :focus-visible{outline:2px solid var(--ug-primary,#6154E8)}
::selection{background:var(--ug-primary,#6154E8);color:white}input,textarea{caret-color:var(--ug-primary,#6154E8)}
.ug-root{position:fixed;inset:0;z-index:var(--ug-z,2147483000);display:flex;align-items:center;justify-content:center;padding:28px;pointer-events:none;color:var(--ug-text,#15151D);font-size:15px;line-height:1.5}
.ug-root.preview{position:absolute}.ug-root.backdrop{background:rgb(21 21 29 / .38);pointer-events:auto}
.ug-surface{position:relative;pointer-events:auto;display:flex;flex-direction:column;width:min(100%,var(--ug-width,560px));max-height:calc(100dvh - 56px);background:var(--ug-bg,#fff);border-radius:var(--ug-radius,20px);box-shadow:0 18px 64px -20px rgb(21 21 29 / .3);overflow:hidden;animation:ug-enter .18s ease-out}
.preview .ug-surface{max-height:calc(100% - 32px)}.ug-root.card{align-items:flex-end;justify-content:flex-end}.ug-root.card.left,.ug-root.panel.left{justify-content:flex-start}.ug-root.panel{justify-content:flex-end;padding:16px}.panel .ug-surface{height:calc(100dvh - 32px)}.preview.panel .ug-surface{height:100%}
.ug-close{position:absolute;right:16px;top:16px;display:grid;place-items:center;min-width:40px;min-height:40px;z-index:2;border:0;border-radius:12px;color:var(--ug-muted,#73738A);background:var(--ug-bg,#fff)}.ug-close:hover{background:color-mix(in srgb,var(--ug-primary,#6154E8) 9%,var(--ug-bg,#fff))}
.ug-content{overflow:auto;padding:36px 32px 28px;scrollbar-width:thin;scrollbar-color:var(--ug-border,#E3E4EE) transparent}.ug-content h2{font-size:24px;line-height:1.25;letter-spacing:-.025em;margin:0 38px 12px 0;font-weight:650;text-wrap:balance}.ug-content p{margin:0 0 20px;color:var(--ug-muted,#73738A);white-space:pre-wrap}.ug-content img{display:block;max-width:100%;width:100%;max-height:220px;object-fit:cover;border-radius:12px;margin-bottom:24px}
.ug-progress{height:3px;background:var(--ug-border,#E3E4EE);flex-shrink:0}.ug-progress span{display:block;height:100%;background:var(--ug-primary,#6154E8);transition:width .18s ease-out}.ug-step{font-size:12px;color:var(--ug-muted,#73738A);margin-bottom:16px;font-variant-numeric:tabular-nums}
.ug-options{display:flex;flex-direction:column;gap:8px;margin:24px 0 8px}.ug-option{position:relative;display:flex;align-items:center;gap:12px;min-height:48px;padding:12px 16px;border:1px solid var(--ug-border,#E3E4EE);border-radius:12px;cursor:pointer;color:var(--ug-text,#15151D);background:transparent;overflow-wrap:anywhere}.ug-option:has(input:checked){border-color:var(--ug-primary,#6154E8);background:color-mix(in srgb,var(--ug-primary,#6154E8) 7%,var(--ug-bg,#fff))}.ug-option:hover{border-color:var(--ug-primary,#6154E8)}.ug-option input{accent-color:var(--ug-primary,#6154E8);width:18px;height:18px;flex-shrink:0}
.ug-scale{display:grid;grid-template-columns:repeat(var(--ug-count,5),minmax(0,1fr));gap:6px;margin:28px 0 8px}.ug-score{display:grid;place-items:center;min-height:44px;border:1px solid var(--ug-border,#E3E4EE);border-radius:10px;background:transparent;color:var(--ug-text,#15151D);font-size:15px;font-variant-numeric:tabular-nums}.ug-score[aria-checked=true]{color:white;background:var(--ug-primary,#6154E8);border-color:var(--ug-primary,#6154E8)}.ug-labels{display:flex;justify-content:space-between;gap:20px;font-size:12px;color:var(--ug-muted,#73738A)}
.ug-input{display:block;resize:vertical;width:100%;border:1px solid var(--ug-border,#E3E4EE);border-radius:12px;padding:13px 15px;min-height:48px;background:var(--ug-bg,#fff);color:var(--ug-text,#15151D);margin-top:20px}.ug-input::placeholder{color:var(--ug-muted,#73738A)}textarea.ug-input{min-height:120px}.ug-error{color:#B42318;font-size:13px;margin-top:12px;min-height:20px}.ug-footer{display:flex;align-items:center;justify-content:flex-end;gap:12px;border-top:1px solid var(--ug-border,#E3E4EE);padding:18px 24px;flex-shrink:0}.ug-button{display:inline-flex;justify-content:center;align-items:center;gap:8px;min-height:44px;border:0;border-radius:12px;background:var(--ug-primary,#6154E8);color:var(--ug-on-primary,#fff);font-weight:600;padding:10px 20px}.ug-button:hover{filter:brightness(.93)}.ug-button.secondary{background:transparent;color:var(--ug-text,#15151D);border:1px solid var(--ug-border,#E3E4EE)}.ug-footer .secondary{margin-right:auto}
.ug-rank{display:flex;align-items:center;gap:8px;border-bottom:1px solid var(--ug-border,#E3E4EE);padding:10px 0}.ug-rank span{flex:1}.ug-rank button{width:44px;height:44px;background:transparent;border:1px solid var(--ug-border,#E3E4EE);border-radius:10px;color:inherit}.ug-success{padding:56px 32px;text-align:center}.ug-success h2{margin-right:0}.ug-success svg{color:var(--ug-primary,#6154E8);margin:0 auto 20px}.ug-list{display:flex;flex-direction:column;gap:0}.ug-list-item{padding:18px 0;border:0;border-bottom:1px solid var(--ug-border,#E3E4EE);background:transparent;color:inherit;text-align:start;width:100%}.ug-list-item strong{display:block;margin-bottom:4px}.ug-list-item small{color:var(--ug-muted,#73738A)}.ug-toolbar{display:flex;gap:12px;align-items:center;margin:20px 0}.ug-toolbar .ug-input{margin:0}.ug-toolbar select{padding:10px;border:1px solid var(--ug-border,#E3E4EE);border-radius:10px;background:transparent;color:inherit}.ug-meta{display:flex;gap:12px;flex-wrap:wrap;font-size:12px;color:var(--ug-muted,#73738A)}.ug-comment{padding:16px 0;border-top:1px solid var(--ug-border,#E3E4EE)}.ug-comment p{color:var(--ug-text,#15151D);margin:8px 0}.ug-link{border:0;background:transparent;color:var(--ug-primary,#6154E8);padding:8px;font-size:13px}
.ug-launcher{pointer-events:auto;position:fixed;right:24px;bottom:max(24px,env(safe-area-inset-bottom));z-index:var(--ug-z,2147483000);min-height:48px;border:0;border-radius:24px;padding:12px 20px;background:var(--ug-primary,#6154E8);color:var(--ug-on-primary,#fff);font:600 14px var(--ug-font,Inter,system-ui,sans-serif);box-shadow:0 8px 28px -8px rgb(21 21 29 / .3)}.ug-launcher.left{right:auto;left:24px}.ug-launch-menu{pointer-events:auto;position:fixed;right:24px;bottom:84px;z-index:var(--ug-z,2147483000);background:var(--ug-bg,#fff);color:var(--ug-text,#15151D);border-radius:16px;box-shadow:0 8px 32px -10px rgb(21 21 29 / .3);padding:8px;min-width:220px}.ug-launch-menu button{display:block;width:100%;padding:12px 16px;border:0;background:transparent;color:inherit;text-align:start;border-radius:10px;font:inherit}.ug-launch-menu button:hover{background:color-mix(in srgb,var(--ug-primary,#6154E8) 8%,var(--ug-bg,#fff))}
@container (max-width:640px){.ug-root{padding:12px;align-items:flex-end}.ug-surface{width:100%;max-height:calc(100dvh - 24px)}.ug-root.survey,.ug-root.requests{padding:0}.survey .ug-surface,.requests .ug-surface{height:100dvh;max-height:100dvh;border-radius:0}.preview.survey .ug-surface,.preview.requests .ug-surface{height:100%;max-height:100%}.ug-content{padding:32px 24px 24px}.ug-content h2{font-size:22px}.ug-footer{padding-bottom:max(18px,env(safe-area-inset-bottom))}.ug-scale.nps{grid-template-columns:repeat(6,minmax(0,1fr))}.ug-scale.ten{grid-template-columns:repeat(5,minmax(0,1fr))}.ug-root.panel{padding:0}.panel .ug-surface{height:100dvh}.ug-toolbar{flex-wrap:wrap}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important}}
@keyframes ug-enter{from{opacity:0;translate:0 6px}to{opacity:1;translate:0 0}}
`
